version: "3.2"

volumes:
  db:

services:

  webserver:
    build:
      context: app
      dockerfile: docker/webserver/Dockerfile
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    env_file: dev.env
    ports:
      - 80:80
      - 443:443
    links:
      - php
    volumes:
      - ./app/code:/code
      - ./app/certbot/conf:/etc/letsencrypt
      - ./app/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./app/certbot/conf:/etc/letsencrypt
      - ./app/certbot/www:/var/www/certbot

  php:
    build:
      context: app
      dockerfile: docker/php/Dockerfile
    env_file: dev.env
    links:
      - db
    volumes:
      - ./app/code:/code

  db:
    image: mariadb:10.1
    env_file: dev.env
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    env_file: dev.env
    links:
      - db
    ports:
      - 8080:80